/**
 * One plain sentence of context per reading, written for a 12 year old.
 *
 * The point is that a reading is never just a list of names. "Numbers 22" means
 * nothing on its own; "a king hires a prophet to curse Israel, and a donkey
 * talks" makes someone want to open it.
 *
 * Keyed by reading number, which is safe because the plan is frozen once
 * generated. A missing sentence falls back to the era description rather than
 * leaving a gap.
 */
export const INTROS: Record<number, string> = {
  // --- How It All Started -------------------------------------------------
  1: 'God makes the world, and the first people break the only rule.',
  2: 'One brother kills the other, and the world turns so bad that God decides to start again.',
  3: 'The flood covers everything, and one family begins the world a second time.',
  4: 'People build a tower to reach heaven, then a rich man called Job loses everything in a single day.',
  5: "Job's friends arrive and begin explaining why this must be his own fault.",
  6: 'Job says he would argue his case if only he could find God.',
  7: 'The friends get harsher, and Job says even they have turned on him.',
  8: 'Job says he knows his defender is alive, and his friends accuse him of crimes.',
  9: 'Job searches everywhere for God, then asks where wisdom can be found.',
  10: 'Job remembers the life he lost, and a young man named Elihu finally speaks.',
  11: 'Elihu argues that God speaks through suffering, not only through good times.',
  12: 'God answers out of a storm and asks Job where he was when the world was made.',
  13: 'Job admits he spoke about things too big for him, then Abram leaves home for a land he has never seen.',
  14: 'Abram rescues his nephew, God promises him a son, and his name becomes Abraham.',
  15: 'Three visitors promise a baby, and the city of Sodom is destroyed.',
  16: 'Isaac is born, and then Abraham is asked to give him back.',
  17: 'Sarah dies, and a servant travels a long way to find Isaac a wife.',
  18: 'Esau sells the rights of the older brother for a bowl of stew.',
  19: "Jacob steals his brother's blessing and runs, and dreams of a stairway to heaven.",
  20: 'Jacob works fourteen years for the wife he wanted.',
  21: 'Jacob escapes from his uncle and wrestles all night with a stranger.',
  22: 'Jacob meets Esau again expecting a fight, and gets a hug instead.',
  23: 'Joseph is given a special coat, tells his brothers his dreams, and they sell him.',
  24: 'Joseph ends up in prison and explains the dreams of two other prisoners.',
  25: "Joseph explains Pharaoh's dream and is put in charge of all Egypt.",
  26: "Joseph's brothers come to buy food and do not recognise him.",
  27: 'Joseph tells his brothers who he really is.',
  28: 'The whole family moves to Egypt.',
  29: 'Jacob blesses his sons and dies, and Joseph forgives his brothers.',

  // --- Out of Egypt -------------------------------------------------------
  30: 'A new king turns Israel into slaves, and God speaks to Moses from a burning bush.',
  31: 'Moses asks Pharaoh to let the people go, and things get worse instead.',
  32: 'The river turns to blood, and frogs, gnats and flies follow.',
  33: 'Animals die, hail falls, and locusts eat whatever is left.',
  34: 'The last and worst plague comes, and Israel eats the first Passover meal.',
  35: 'The sea opens, the army drowns behind them, and Israel sings.',
  36: 'Food falls from the sky and water comes out of a rock.',
  37: 'God speaks from the mountain and gives the Ten Commandments.',
  38: 'More laws for ordinary life, and the people promise to keep them.',
  39: 'Instructions for the tent where God will live among the people.',
  40: 'The altar, the courtyard, and the clothes the priests have to wear.',
  41: 'How the priests are set apart, and the oil and incense for the tent.',
  42: 'The people melt their gold into a calf while Moses is up the mountain.',
  43: 'Moses goes back up, comes down with his face shining, and everyone brings gifts.',
  44: 'The craftsmen build the tent and the golden chest exactly as they were told.',
  45: "The courtyard and the priests' clothes are finished.",
  46: 'The tent goes up, God fills it, and the first offerings are explained.',
  47: 'What to do when you do wrong without meaning to.',
  48: "The priests' instructions for each kind of offering.",
  49: 'Aaron and his sons become priests, and fire comes down from God.',
  50: 'Two priests die for disobeying, and rules follow about clean and unclean food.',
  51: 'How to tell a dangerous skin disease from a harmless one.',
  52: 'How someone who has been healed is welcomed back into the camp.',
  53: 'One day every year, the whole nation is made clean.',
  54: 'Love your neighbour as yourself, among many other laws.',
  55: 'Punishments, and the higher standard priests have to live by.',
  56: 'The festivals Israel has to keep every year.',
  57: 'Every fiftieth year, debts are cancelled and land goes back to its family.',
  58: 'What follows obeying God, and what follows walking away.',
  59: 'Israel is counted, and each tribe is given its own place in the camp.',
  60: 'One tribe is given the job of carrying the tent everywhere they go.',
  61: 'The blessing the priests are told to say over the people.',
  62: 'Twelve leaders bring identical gifts, one leader a day for twelve days.',
  63: 'A cloud lifts off the tent, and Israel starts marching.',
  64: 'Twelve spies explore the land, and ten come back terrified.',
  65: 'The people refuse to go in, so they will wander for forty years.',
  66: 'A rebellion against Moses ends with the ground opening up.',
  67: 'Moses hits a rock instead of speaking to it, and loses his place in the land.',
  68: 'A king hires a prophet to curse Israel, and a donkey talks.',
  69: 'Balaam blesses Israel every single time he tries to curse them.',
  70: 'The new generation is counted, and Joshua is chosen to take over.',
  71: 'The offerings for every day of the year and every festival.',
  72: 'Promises and how binding they are, then war with Midian.',
  73: 'Two tribes ask to settle east of the river, and the whole journey is listed.',
  74: 'The borders of the land, and cities where someone can run to for safety.',
  75: 'Moses retells the whole story to the children of the people who left Egypt.',
  76: 'Moses begs them never to forget what they saw at the mountain.',
  77: 'The Ten Commandments again, and the command to love God with everything you have.',
  78: 'Do not forget God once you are full, comfortable and safe.',
  79: 'A blessing and a curse are put in front of them to choose between.',
  80: 'Laws about false prophets, food, debts and setting slaves free.',
  81: 'Rules for festivals, judges, kings and prophets.',
  82: 'Laws about courts, going to war, and unsolved murders.',
  83: 'Everyday laws about property, marriage and treating people fairly.',
  84: 'Honest weights, first harvests, and words shouted between two mountains.',
  85: 'A long list of what obeying brings, and what turning away brings.',
  86: 'Moses puts life and death in front of them and tells them to choose life.',
  87: 'Moses hands over to Joshua and teaches Israel a song to remember.',
  88: 'Moses blesses the tribes, sees the land from a mountain, and dies.',

  // --- A Land of Their Own ------------------------------------------------
  89: 'Joshua takes over, spies go into Jericho, and the river stops flowing.',
  90: 'Israel walks around Jericho for seven days and the walls fall down.',
  91: 'One man steals what he was told not to, and the whole army loses a battle.',
  92: 'A local people trick Israel into a treaty, and the sun stands still.',
  93: 'The fighting ends and the land starts being shared out between the tribes.',
  94: 'Caleb, now eighty five, asks for the hill country with the giants on it.',
  95: 'The tribes are slow to claim what they have been given.',
  96: 'The last tribes get their land, and cities are set aside for safety.',
  97: 'An altar by the river nearly starts a civil war.',
  98: 'Joshua tells Israel to choose who they will serve, and then he dies.',
  99: 'The new generation forgets God, and the pattern of the judges begins.',
  100: 'Deborah wins a battle and sings about it, and Gideon hides in a winepress.',
  101: 'Gideon beats an army with three hundred men, jars and torches.',
  102: "Gideon's son kills his brothers and makes himself king.",
  103: 'Jephthah wins a battle after making a promise he should not have made.',
  104: 'Samson is born, and he is strong and very foolish.',
  105: 'Samson kills a thousand men with a donkey bone.',
  106: "A tribe steals another man's idols and priest on their way to a new home.",
  107: 'Israel almost destroys one of its own tribes.',
  108: "A foreign widow refuses to leave her mother in law, and becomes David's great grandmother.",

  // --- The First Kings ----------------------------------------------------
  109: 'A woman prays for a son and gives him back to God.',
  110: 'God calls Samuel in the night, and the ark is captured in battle.',
  111: 'The ark comes home, and Israel demands a king like everyone else has.',
  112: 'Saul goes looking for lost donkeys and comes back as king.',
  113: 'Saul wins his first battle, then gets impatient and offers a sacrifice himself.',
  114: 'Jonathan attacks an army with one soldier, and Saul makes a stupid oath.',
  115: 'Saul disobeys and loses the throne, and a shepherd boy is anointed in secret.',
  116: 'David kills Goliath with a stone.',
  117: 'Saul turns on David and throws a spear at him.',
  118: 'Jonathan warns David to run, and David writes a song about the men watching his house.',
  119: 'David runs, pretends to be mad to survive, and hides in caves.',
  120: 'David spares the life of the king who is hunting him, and writes about it.',
  121: 'More songs from the caves, then a rich fool insults David and his wife saves him.',
  122: 'David spares Saul a second time, and Saul visits a witch in desperation.',
  123: 'Saul dies on the mountain, and the writer of Chronicles tells it too.',
  124: "David mourns the man who hunted him, and civil war begins.",
  125: 'Abner is murdered, and the family lists of Israel begin.',
  126: 'The families of Judah, including the line that leads to David.',
  127: 'The families east of the river, and the tribe of the priests.',
  128: 'The rest of the family lists, and the people who came back to Jerusalem.',
  129: 'David becomes king over the whole nation and captures Jerusalem.',
  130: 'The ark is brought to Jerusalem, and David dances all the way.',
  131: 'David gives the singers a song of thanks, and four more psalms from that day.',
  132: 'God promises David a family line that will never end.',
  133: 'David looks after his dead friend\'s crippled son, then goes to war.',
  134: 'David takes another man\'s wife and has him killed, and a prophet tells him a story about a lamb.',
  135: 'David\'s two songs of sorrow, then trouble starts inside his own family.',
  136: 'Absalom comes home and quietly steals the hearts of the nation.',
  137: 'David runs from his own son, and writes a song while running.',
  138: 'Absalom dies in a tree, and David weeps for him.',
  139: 'A rebellion is put down, and old debts from Saul are paid.',
  140: 'David\'s great song of rescue, written twice into the Bible.',
  141: 'David\'s last words, and a census that brings a plague.',
  142: 'David buys a threshing floor, and gets everything ready for a temple he will never build.',
  143: 'The singers and gatekeepers are organised for the temple.',
  144: 'Songs about two roads, a shepherd king, and asking God how long.',
  145: 'The heavens tell God\'s glory, and the Lord is my shepherd.',
  146: 'Songs about waiting, forgiveness and being kept safe.',
  147: 'Do not worry about people who do wrong, because it does not last.',
  148: 'He lifted me out of the pit, and God is our refuge and strength.',
  149: 'Clap your hands, and create in me a clean heart.',
  150: 'Songs of trust written from dry and difficult places.',
  151: 'Save me, God, the water is up to my neck.',
  152: 'Songs of a king, and a set of praises David wrote late in life.',
  153: 'David hands Solomon the plans for the temple in front of the whole nation.',
  154: 'One son tries to grab the throne, and Solomon is made king instead.',
  155: 'David dies, and Solomon settles the old scores his father left behind.',
  156: 'Solomon asks for wisdom instead of riches, and settles the case of two mothers.',
  157: 'A prayer for the king, then a long love song between a bride and a groom.',
  158: 'The love song ends, and Solomon starts writing down what he has learned.',
  159: 'Trust God with all your heart, and do not lean on your own understanding.',
  160: 'Warnings about the wrong friends, and wisdom calling out in the street.',
  161: 'Short sayings about money, words, honesty and pride.',
  162: 'A gentle answer turns away anger.',
  163: 'Sayings about work, drink, anger and bringing up children.',
  164: 'Do not boast about tomorrow, because you do not know what it holds.',
  165: 'Sayings collected by King Hezekiah\'s men, and two writers nobody knows.',
  166: 'A poem about a remarkable woman, then Solomon starts building the temple.',
  167: 'The temple is built, without the sound of a hammer on the site.',
  168: 'The pillars, the sea of bronze, and everything inside the temple.',
  169: 'The ark is carried in, and the glory of God fills the building.',
  170: 'Solomon prays and asks God to hear his people whenever they turn back.',
  171: 'Fire falls from heaven, and songs about living in the shelter of God.',
  172: 'Sing to the Lord a new song, and bless the Lord, my soul.',
  173: 'A song about all God has made, then Solomon\'s wealth and building.',
  174: 'The queen of Sheba comes to test Solomon and leaves speechless.',
  175: 'Everything is meaningless, says the wisest man alive.',
  176: 'There is a time for everything, and two are better than one.',
  177: 'Enjoy your life and your work, because that is God\'s gift.',
  178: 'Remember God while you are young, then Solomon turns away in his old age.',

  // --- The Kingdom Splits in Two ------------------------------------------
  179: "Solomon's son refuses to lighten the load, and ten tribes walk away.",
  180: 'A prophet is killed by a lion for believing a lie.',
  181: 'Egypt raids Jerusalem and takes the golden shields Solomon made.',
  182: 'A king with a smaller army wins because he calls out to God first.',
  183: 'Asa tears down the idols, then hires an army instead of trusting God.',
  184: 'Ahab marries Jezebel, and a prophet called Elijah stops the rain.',
  185: 'Elijah faces four hundred and fifty prophets on a mountain, then runs away scared.',
  186: 'Ahab lets a defeated king go, then has a neighbour killed for a vegetable garden.',
  187: 'A prophet tells the truth nobody wants, and Ahab dies from a random arrow.',
  188: 'A choir leads an army into battle, and Elijah calls down fire.',
  189: 'Elijah is taken up in a whirlwind, and Elisha takes his place.',
  190: 'Endless oil, a boy raised from the dead, and a general healed in a river.',
  191: 'An axe head floats, an invisible army appears, and a siege ends overnight.',
  192: 'A cruel king takes the throne in Judah and nobody is sorry when he dies.',
  193: 'Jehu is anointed and drives to Jezreel like a madman.',
  194: 'Jehu destroys the worship of Baal, and a grandmother murders her way to the throne.',
  195: 'Edom cheers while Jerusalem is robbed, and a hidden baby becomes king at seven.',
  196: 'The temple is repaired with a collection box, then locusts strip the land bare.',
  197: 'Joel calls the nation to turn back, and Elisha dies.',
  198: 'A king wins a battle and then picks a fight he cannot win.',
  199: 'Jonah runs from God, gets swallowed, and is furious when the city repents.',
  200: 'A strong king ruins it all by pushing into the temple himself.',
  201: 'Amos, a shepherd, tells a rich nation that God has seen how it treats the poor.',
  202: 'Let justice roll down like a river.',
  203: 'Hosea is told to marry a woman who will break his heart, as a picture.',
  204: 'God says his people know him about as well as morning mist knows the sun.',
  205: 'When Israel was a child, I loved him, and I taught him to walk.',
  206: 'Hosea ends with hope, and songs asking why the wicked seem to win.',
  207: 'A long song retelling the whole story of Israel so nobody forgets.',
  208: 'How lovely is your dwelling place, and songs from the temple singers.',
  209: 'A king sacrifices his own son, and Micah begins to preach.',
  210: 'Do justly, love mercy, and walk humbly with your God.',
  211: 'Micah ends, and the northern kingdom is destroyed and carried away.',

  // --- Only Judah Left ----------------------------------------------------
  212: 'Isaiah sees God in the temple and says: here I am, send me.',
  213: 'A song about a vineyard, and a promise that a child will be born.',
  214: 'The people who walked in darkness have seen a great light.',
  215: 'A shoot will grow from a cut down stump, and the wolf will live with the lamb.',
  216: 'Warnings for every nation around Judah, one after another.',
  217: 'Isaiah walks barefoot for three years as a living warning.',
  218: 'God will swallow up death for ever and wipe away every tear.',
  219: 'Woe to the proud, and a promise of a stone laid in Zion.',
  220: 'Judah wants to trust Egypt instead of God, and Isaiah says it will not work.',
  221: 'The desert will bloom, and a young king reopens the temple doors.',
  222: 'Hezekiah invites the whole nation to a Passover nobody has kept for years.',
  223: 'The Assyrian army surrounds Jerusalem and mocks God at the city wall.',
  224: 'Hezekiah spreads the threatening letter out before God, and the army is destroyed.',
  225: 'Hezekiah is given fifteen more years, then shows the treasury to the wrong visitors.',
  226: 'Do not be afraid, for I have called you by name.',
  227: 'Isaiah names the king who will send the exiles home, long before he is born.',
  228: 'Babylon falls, and God says he has not forgotten his people.',
  229: 'He was pierced for our wrongs, and by his wounds we are healed.',
  230: 'Come, everyone who is thirsty, and buy without money.',
  231: 'The fasting God wants is to feed the hungry and free the trapped.',
  232: 'Good news for the poor, and the year of the Lord\'s favour.',
  233: 'New heavens and a new earth, and the old troubles forgotten.',
  234: 'The worst king Judah ever had, and a warning that Nineveh is finished.',
  235: 'Nineveh falls, and a lost book of the law is found during repairs.',
  236: 'Josiah destroys every idol in the country, then dies in a battle he was warned about.',
  237: 'Zephaniah warns that the day of the Lord is close.',

  // --- Jerusalem Falls ----------------------------------------------------
  238: 'Habakkuk asks God why he stays silent, and Jeremiah is called as a boy.',
  239: 'God says his people have swapped a fresh spring for cracked buckets.',
  240: 'A warning from the north, and nobody wants to hear it.',
  241: 'Jeremiah stands at the temple gate and tells people the building will not save them.',
  242: 'Is there no medicine in Gilead? Jeremiah weeps for his people.',
  243: 'Idols are like scarecrows in a melon patch, and cannot walk or speak.',
  244: 'Daniel is taken to Babylon and explains a dream nobody else can.',
  245: 'Three friends refuse to bow and walk out of a furnace unburnt.',
  246: 'Jeremiah is told to stop praying for the nation, and he refuses to be quiet.',
  247: 'Jeremiah watches a potter reshape a ruined pot on the wheel.',
  248: 'Jeremiah is beaten and put in the stocks, and says he wishes he had never been born.',
  249: 'A promise of a good king from David\'s line, and two baskets of figs.',
  250: 'Ezekiel sees wheels of fire by a canal in Babylon and is told to eat a scroll.',
  251: 'Ezekiel acts out the siege of Jerusalem with a brick and a hair.',
  252: 'Seventy years, says Jeremiah, and the crowd wants him executed for it.',
  253: 'Jeremiah wears an ox yoke, and writes to the exiles telling them to plant gardens.',
  254: 'A promise of return, and God\'s glory begins to leave the temple.',
  255: 'Ezekiel watches the glory of God move to the doorway and then away.',
  256: 'A new agreement is promised, written on hearts instead of stone.',
  257: 'Jeremiah buys a field while the enemy is at the gates, as a sign of hope.',
  258: 'Even in prison Jeremiah is told to promise that the city will be rebuilt.',
  259: 'A king cuts up Jeremiah\'s scroll and burns it, so Jeremiah writes it again.',
  260: 'Jeremiah is lowered into a muddy cistern and left to die.',
  261: 'False prophets whitewash a wall that is about to fall down.',
  262: 'God tells the story of Jerusalem as a rescued child who forgot who saved her.',
  263: 'Nobody is punished for their parent\'s wrongs, only their own.',
  264: 'Babylon takes Jerusalem, and the temple is burned.',
  265: 'The walls come down, and the survivors are marched away.',
  266: 'How lonely sits the city that was once full of people.',
  267: 'His mercies are new every morning, written from the middle of a ruin.',
  268: 'By the rivers of Babylon we sat and wept, and Jeremiah is set free.',
  269: 'The governor left behind is murdered, and the survivors run to Egypt.',
  270: 'Jeremiah is dragged to Egypt and keeps telling the truth there.',
  271: 'A song about lion cubs, and a retelling of a whole rebellious history.',
  272: 'A sword is sharpened, and God looks for one person to stand in the gap.',
  273: 'Two sisters, and the day Ezekiel\'s wife dies and he is told not to mourn.',
  274: 'Messages for Egypt, the Philistines, Moab and Ammon.',
  275: 'Messages for Edom, Damascus and Babylon itself.',
  276: 'Babylon will fall, and the scroll saying so is thrown into the Euphrates.',
  277: 'Messages for the nations that cheered when Jerusalem fell.',
  278: 'A message for the proud king of Tyre, and for Egypt.',
  279: 'Egypt is a great tree that is about to be cut down.',
  280: 'A proud king eats grass like an ox, and a hand writes on a wall.',
  281: 'Daniel is thrown to the lions, and Ezekiel is made a watchman.',
  282: 'Bad shepherds are sacked, and God says he will shepherd the flock himself.',
  283: 'A valley of dry bones stands up and lives.',
  284: 'A last enemy comes from the north and is defeated.',
  285: 'Ezekiel is shown a new temple and a man measuring it with a rod.',
  286: 'The measurements continue, room by room.',
  287: 'The glory of God comes back and fills the temple again.',
  288: 'How the land around the temple is to be shared out.',
  289: 'A river flows from the temple and everything it touches lives.',
  290: 'Four beasts come out of the sea, and one like a son of man is given a kingdom.',
  291: 'Daniel prays for his people, and is told how long the waiting will be.',
  292: 'Kings rise and fall, and Daniel is told to go his way until the end.',

  // --- Coming Home --------------------------------------------------------
  293: 'Cyrus lets the exiles go home, and the foundation of the temple is laid.',
  294: 'The work is stopped by enemies, and Haggai asks why everyone has panelled houses.',
  295: 'Zechariah sees eight visions in one night.',
  296: 'Your king comes to you, humble and riding on a donkey.',
  297: 'A shepherd is struck and the sheep scatter.',
  298: 'A promise that God will be king over all the earth, and the temple is finished.',
  299: 'A king throws out his queen, and a Jewish orphan is chosen instead.',
  300: 'Esther risks her life to walk in uninvited, for such a time as this.',
  301: 'The plot fails, and the man who planned it dies on the pole he built.',
  302: 'Ezra travels to Jerusalem to teach the law, refusing an armed escort.',
  303: 'Ezra weeps over how far the people have drifted, and Nehemiah hears about the broken wall.',
  304: 'Nehemiah inspects the ruins at night and organises the rebuilding.',
  305: 'The builders work with a tool in one hand and a weapon in the other.',
  306: 'The wall is finished in fifty two days, and Ezra reads the law out loud.',
  307: 'The people confess, and retell their whole history back to God.',
  308: 'Jerusalem is repopulated, and the wall is dedicated with two huge choirs.',
  309: 'Nehemiah comes back and finds old habits returning, and Malachi begins.',
  310: 'Bring the whole tithe, and see if God does not open the windows of heaven.',
  311: 'Praise songs sung at the great festivals.',
  312: 'The longest chapter in the Bible, all about loving God\'s word.',
  313: 'The songs of ascents, and five final psalms of praise. The Old Testament ends.',
};

export const introFor = (n: number): string | null => INTROS[n] ?? null;
